{{- if eq .Values.application.type "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-template-chart.fullname" . }}
  labels:
    {{- include "base-template-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.deployment.hpa.enabled }}
  replicas: {{ .Values.deployment.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base-template-chart.selectorLabels" . | nindent 6 }}
  {{- if .Values.deployment.strategy }}
  strategy:
    {{- toYaml .Values.deployment.strategy | nindent 8 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "base-template-chart.labels" . | nindent 8 }}
  {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "base-template-chart.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.application.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- if .Values.persistence.enabled }}
            - name: {{ .Values.persistence.name }}
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          envFrom:
            {{- if .Values.envFromConfigMaps }}
            {{- range $configMap := .Values.envFromConfigMaps }}
            - configMapRef:
                name: {{ $configMap.name }}
            {{- end }}
            {{- end }}
    
            {{- if .Values.externalSecrets }}
            {{- range $externalSecret := .Values.externalSecrets.secrets }}
            - secretRef:
                name: {{ $externalSecret.name }}
            {{- end }}
            {{- end }}

            {{- if .Values.envFromSecrets }}
            {{- range $secret := .Values.envFromSecrets }}
            - secretRef:
                name: {{ $secret.name }}
            {{- end }}
            {{- end }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- if .Values.persistence.enabled }}
        - name: {{ .Values.persistence.name }}
          persistentVolumeClaim:
            claimName: {{ include "base-template-chart.fullname" . }}-data
        {{- end }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}