{{- if .Values.externalSecrets }}
{{- range $externalSecret := .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault-oke
    kind: ClusterSecretStore
  target:
    name: {{ $externalSecret.name }}
  dataFrom:
  - extract:
      key: {{ $externalSecret.path }}
{{- end }}
{{- end }}
