{{- if .Values.externalSecrets }}
{{- $labels := include "base-template-chart.labels" . -}}
{{- $apiVersion := .Values.externalSecrets.apiVersion | default "external-secrets.io/v1" -}}
{{- $storeKind := .Values.externalSecrets.secretStoreKind | default "ClusterSecretStore" -}}
{{- range $externalSecret := .Values.externalSecrets.secrets }}
---
apiVersion: {{ $apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  refreshInterval: {{ $externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $externalSecret.secretStore }}
    kind: {{ $externalSecret.secretStoreKind | default $storeKind }}
  target:
    name: {{ $externalSecret.name }}
  dataFrom:
  - extract:
      key: {{ $externalSecret.key | default $externalSecret.path }}
{{- end }}
{{- end }}
