{{- range $externalSecret := .Values.externalSecrets.secrets }}
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name }}
  namespace: {{ $.Values.application.namespace }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ $externalSecret.name }}
  dataFrom:
  - extract:
      key: {{ $.Values.application.environment }}/{{ $.Values.application.namespace }}/{{ $externalSecret.name }}
{{- end }}
{{- end }}